fruits = []
f1 = input("PLZ WRITE A FRUIT OF YOUR CHOICE")
fruits.append(f1)
f2 = input("PLZ WRITE A FRUIT OF YOUR CHOICE")
fruits.append(f2)
f3 = input("PLZ WRITE A FRUIT OF YOUR CHOICE")
fruits.append(f3)
f4 = input("PLZ WRITE A FRUIT OF YOUR CHOICE")
fruits.append(f4)
f5 = input("PLZ WRITE A FRUIT OF YOUR CHOICE")
fruits.append(f5)
f6 = input("PLZ WRITE A FRUIT OF YOUR CHOICE")
fruits.append(f6)
f7 = input("PLZ WRITE A FRUIT OF YOUR CHOICE")
fruits.append(f7) 
print(fruits) 