# s = {}
# name=input("name plz:")
# lang=input("lang plz")
# s.update({name: lang})
# name=input("name plz:")
# lang=input("lang plz")
# s.update({name: lang})
# name=input("name plz:")
# lang=input("lang plz")
# s.update({name: lang})
# name=input("name plz:")
# lang=input("lang plz")
# s.update({name: lang})
# print(s)

# colors = {}
# name=input("enter the name")
# fav=input("enter the color: ")
# colors.update({name: fav})
# name=input("enter the name")
# fav=input("enter the color: ")
# colors.update({name: fav})
# name=input("enter the name")
# fav=input("enter the color: ")
# colors.update({name: fav})
# name=input("enter the name")
# fav=input("enter the color: ")
# colors.update({name: fav}) 
# print(colors)
