name: Continuous Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-registry:
    runs-on: ubuntu-latest
    # This gives your pipeline permission to save files inside your GitHub account securely
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log into GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Production Container
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/my-prod-app:latest
